apis:
  payment:
    root: ../src/paymentAPI.yaml
    output: ../paymentAPI.yaml
  account:
    root: ../src/accountAPI.yaml
    output: ../accountAPI.yaml
  webhook-account:
    root: ../src/accountAPI-event-notification-webhook-yaml.yaml
    output: ../accountAPI-event-notification-webhook-yaml.yaml
  webhook-payment:
    root: ../src/paymentAPI-event-notification-webhook-yaml.yaml
    output: ../paymentAPI-event-notification-webhook-yaml.yaml
