openapi: 3.0.0
info:
  version: 6.0.0
  title: event-notification webhook
  description: |
    This is the specification of the 'event-notification' webhook.

    Disclaimer:
    - This specification file is to be interpreted as pseudo-code.
    - Once the structure and endpoints are agreed:
    * all mandatory and optional headers will have to be added
    * all error responses will have to be specified
    * example requests and responses will need to be improved
    * missing details in descriptions will have to be added
  contact:
    email: info@common-api.ch
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://webhook-notification.common-api.ch
externalDocs:
  description: Find out more about SFTI API specifications.
  url: https://www.common-api.ch
tags:
  - name: event-notification-webhook
    description: Event notification webhook operations.
security:
  - OAuth2:
      - read
      - write
paths:
  /event-notifications:
    post:
      tags:
        - event-notification-webhook
      summary: Push notification towards service users
      description: Push notifications for subscribed event notifications.
      operationId: postEventNotification
      parameters:
        - $ref: '#/components/parameters/correlation'
        - $ref: '#/components/parameters/api_version'
        - $ref: '#/components/parameters/event_type'
        - $ref: '#/components/parameters/event_id'
        - $ref: '#/components/parameters/event_created'
        - $ref: '#/components/parameters/event_subscription_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventNotification'
      responses:
        '202':
          description: Notification accepted.
          headers:
            X-Correlation-ID:
              $ref: '#/components/headers/X-Correlation-ID'
        '400':
          $ref: '#/components/responses/standard400'
        '404':
          $ref: '#/components/responses/standard404'
        '429':
          $ref: '#/components/responses/standard429'
        '500':
          $ref: '#/components/responses/standard500'
        '501':
          $ref: '#/components/responses/standard501'
        '503':
          $ref: '#/components/responses/standard503'
        '504':
          $ref: '#/components/responses/standard504'
components:
  schemas:
    CommonErrorResponse:
      title: Common Error Response
      description: The common error response object.
      type: object
      required:
        - detail
        - title
        - type
      properties:
        detail:
          type: string
          description: The details about the common error response.
          example: Detailed problem description with respect to the current request
        title:
          type: string
          description: The title of the common error response.
          example: This is the general problem description
        type:
          $ref: '#/components/schemas/CommonErrorType'
        instance:
          type: string
          description: The path to the corresponding resource.
          example: path/to/corresponding/resource
        status:
          type: integer
          format: int32
          description: The HTTP status code generated by the origin server.
          example: 404
    CommonErrorType:
      title: Common Error Type
      description: Error Types for CommonErrorResponse.
      type: string
      enum:
        - /problems/INVALID_PAYLOAD
        - /problems/MALFORMED_PAYLOAD
        - /problems/INVALID_TOKEN
        - /problems/EXPIRED_TOKEN
        - /problems/INSUFFICIENT_PRIVILEGES
        - /problems/NO_ACCESS_TO_RESOURCE
        - /problems/RESOURCE_DOES_NOT_EXIST
        - /problems/RESOURCE_NOT_READY
        - /problems/RESOURCE_TOO_LARGE
        - /problems/WRONG_METHOD
        - /problems/OPERATION_NOT_ALLOWED
        - /problems/TECHNICAL_ERROR
        - /problems/NOT_IMPLEMENTED
        - /problems/SERVICE_UNAVAILABLE
        - /problems/SUBSCRIPTION_NOT_FOUND
        - /problems/SUBSCRIPTION_ALREADY_EXISTS
        - /problems/TOO_MANY_REQUESTS
      example: /problems/TECHNICAL_ERROR
    EventNotification:
      type: object
      properties:
        createdAt:
          type: string
          example: 2022-10-26T07:58:30.996+0100
        eventSubscriptionId:
          $ref: '#/components/schemas/EventNotificationId'
        eventType:
          type: string
          example: accounts:listUpdated
        id:
          $ref: '#/components/schemas/EventNotificationId'
        resourceLink:
          type: string
          example: /api/bankingservices/b-link/account-information-service/v7/accounts
        version:
          type: string
          example: '1.0'
    EventNotificationId:
      type: string
      example: 120066c9-58a1-432b-aa60-712fae7f143e
  responses:
    standard400:
      headers:
        Content-Language:
          $ref: '#/components/headers/Content-Language'
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: |
        Bad Request - The format of the request was invalid.

        Examples:
        - InvalidPayload:
        type: /problems/INVALID_PAYLOAD
        title: Payload does not comply with API specification
        detail: Malformed JSON
        instance: path/to/corresponding/resource

        - InvalidParameter:
        type: /problems/INVALID_PAYLOAD
        title: Invalid parameter values have been detected
        detail: Sent data could not processed
        instance: path/to/corresponding/resource

        - MissingId:
        type: /problems/INVALID_PAYLOAD
        title: The payload was not valid
        detail: ID is missing
        instance: path/to/corresponding/resource
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/CommonErrorResponse'
    standard404:
      headers:
        Content-Language:
          $ref: '#/components/headers/Content-Language'
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: |
        Not Found - Either the endpoint does not exist or a requested resource is not
        yet available (e.g., account statements)

        Examples:
        - InvalidAccounts:
        type: /problems/INSUFFICIENT_PRIVILEGES
        title: Insufficient privileges to access resource
        detail: The provided token does not grant access to the requested account
        instance: path/to/corresponding/resource

        - InvalidToken:
        type: /problems/INSUFFICIENT_PRIVILEGES
        title: Insufficient privileges to access resource
        detail: The provided token is not valid
        instance: path/to/corresponding/resource

        - WrongEndpointUrl:
        type: /problems/TECHNICAL_ERROR
        title: URL not found
        detail: The requested endpoint does not exist
        instance: path/to/corresponding/resource

        - NoIntradayDataSupported:
        type: /problems/NOT_IMPLEMENTED
        title: Feature is not implemented
        detail: This interface does not support intraday data
        instance: path/to/corresponding/resource
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/CommonErrorResponse'
    standard429:
      headers:
        Content-Language:
          $ref: '#/components/headers/Content-Language'
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: |
        When an SU sends too many lookup or polling requests in a given amount of time the SP shall respond with HTTP 429 (Too many requests).
        This response may contain a Retry-After header indicating how long the SU must wait before making a new request.
        (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429).
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/CommonErrorResponse'
          example:
            type: /problems/TOO_MANY_REQUESTS
            title: too many requests
            detail: too many requests were sent in a short period of time
            instance: path/to/corresponding/resource
    standard500:
      headers:
        Content-Language:
          $ref: '#/components/headers/Content-Language'
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: |
        Internal Server Error - The server encountered an unexpected condition that
        prevented it from fulfilling the request.

        Examples:
        - TechnicalServerError:
        type: /problems/TECHNICAL_ERROR
        title: Technical error on server side
        detail: Processing yielded a technical error
        instance: path/to/corresponding/resource

        - ResourceTooLarge:
        type: /problems/RESOURCE_TOO_LARGE
        title: Generated resource was too large
        detail: The generated resource exceeded the size limit
        instance: path/to/corresponding/resource
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/CommonErrorResponse'
    standard501:
      headers:
        Content-Language:
          $ref: '#/components/headers/Content-Language'
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: |
        Not Implemented - The server does not support the functionality required to fulfill the request.

        Examples:
        - EndpointNotImplemented:
        type: /problems/NOT_IMPLEMENTED
        title: Target endpoint is not implemented
        detail: This endpoint is not implemented
        instance: path/to/corresponding/resource
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/CommonErrorResponse'
    standard503:
      headers:
        Content-Language:
          $ref: '#/components/headers/Content-Language'
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: Service Unavailable - The server is currently unable to handle the request due to a temporary overload or scheduled maintenance.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/CommonErrorResponse'
    standard504:
      headers:
        Content-Language:
          $ref: '#/components/headers/Content-Language'
        X-Correlation-ID:
          $ref: '#/components/headers/X-Correlation-ID'
      description: Gateway Timeout.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/CommonErrorResponse'
          example:
            type: /problems/TECHNICAL_ERROR
            title: gateway timeout
            detail: the request could not be completed in time
            instance: path/to/corresponding/resource
  parameters:
    api_version:
      in: header
      name: X-CorApi-API-Version
      description: The API Version.
      required: false
      schema:
        type: string
      example: '1.0'
    correlation:
      in: header
      name: X-Correlation-ID
      description: Unique ID (defined by the caller) which will be reflected back in the response.
      required: true
      schema:
        type: string
    event_created:
      in: header
      name: X-CorAPI-Event-Created-At
      description: The Event-Created Date
      required: false
      schema:
        type: string
        format: date-time
      example: '2024-05-28T13:44:53Z'
    event_id:
      in: header
      name: X-CorApi-Event-ID
      description: The Event-ID
      required: false
      schema:
        type: string
      example: 7c5f40fc-1b29-4263-a2dd-e127a22a947f
    event_subscription_id:
      in: header
      name: X-CorApi-Event-Subscription-ID
      description: The ID of the Subscription the event was created for
      required: false
      schema:
        type: string
      example: 7c5f40fc-1b29-4263-a2dd-e127a22a947f
    event_type:
      in: header
      name: X-CorApi-Event-Type
      description: The Event-Type
      required: false
      schema:
        type: string
      example: accounts:listUpdated
  headers:
    Content-Language:
      description: Response language - always en.
      schema:
        type: string
    X-Correlation-ID:
      description: Client defined ID from request to correlates HTTP requests between a client and server.
      schema:
        type: string
        example: f058ebd6-02f7-4d3f-942e-904344e8cde5
