name: Issue Report
description: Report a new issue
title: "[Issue]: "
labels: ["new"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: issue_description
    attributes:
      label: Issue description
      description: Plese provide a clear and concise description of the issue, showing what should be changed.
      placeholder: Clear and concise description of the issue
    validations:
      required: true
  - type: textarea
    id: issue_reasoning
    attributes:
      label: Issue reasoning
      description: Please provide an explanation of why the proposed changes are necessary, including the benefits or issues they address.
      placeholder: Explanation of why the proposed changes are necessary
    validations:
      required: true
  - type: textarea
    id: issue_request
    attributes:
      label: Request
      description: Please provide a description of the request on which the working group is to decide.
      placeholder: Request description the working group is to decide.
    validations:
      required: true      
  - type: dropdown
    id: affected_api
    attributes:
      label: Affected API's
      description: Which API's are affected by the issue?
      options:
        - AIS - accountAPI
        - PSS - paymentAPI
        - Both
        - None (issue does not affect the API's but other components)
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Contribution Guidelines](https://github.com/swissfintechinnovations/ca-payment/blob/main/CONTRIBUTING.md#how-to-contribute). 
      options:
        - label: I agree to follow this project's Contribution Guidelines
          required: true
