openapi: 3.0.0
info:
  version: 6.0.0
  title: event-notification webhook
  description: >
    This is the specification of the 'event-notification' webhook.
    Disclaimer:
      - This specification file is to be interpreted as pseudo-code
      - once the structure and endpoints are agreed<
        * all mandatory and optional headers will have to be added
        * all error responses will have to be specified
        * example requests/responses will need to be improved
        * missing details in descriptions will have to be added
  contact:
    email: info@common-api.ch
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://webhook-notification.common-api.ch
tags:
  - name: event-notification-webhook
    description: Event notification webhook operations.
paths:
  /event-notifications:
    post:
      description: Send notification
      parameters:
        - $ref: '#/components/parameters/correlation_in_header'
        - $ref: '#/components/parameters/api_version_in_header'
        - $ref: '#/components/parameters/event_type_in_header'
        - $ref: '#/components/parameters/event_id_in_header'
        - $ref: '#/components/parameters/event_created_in_header'
        - $ref: '#/components/parameters/event_subscription_id_in_header'
      tags:
        - Notification Webhook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventNotification'
      responses:
        '202':
          description: event-notification accepted
          headers:
            X-Correlation-ID:
              $ref: '#/components/headers/X-Correlation-ID'
        '400':
          $ref: '#/components/responses/standard400'
        '404':
          $ref: '#/components/responses/standard404'
        '405':
          $ref: '#/components/responses/standard405'
        '429':
          $ref: '#/components/responses/standard429'
        '500':
          $ref: '#/components/responses/standard500'
        '501':
          $ref: '#/components/responses/standard501'
        '503':
          $ref: '#/components/responses/standard503'
        '504':
          $ref: '#/components/responses/standard504'
