openapi: 3.0.0
info:
  version: 6.0.0
  title: event-notification webhook
  description: |
    This is the specification of the 'event-notification' webhook.

    Disclaimer:
    - This specification file is to be interpreted as pseudo-code.
    - Once the structure and endpoints are agreed:
    * all mandatory and optional headers will have to be added
    * all error responses will have to be specified
    * example requests and responses will need to be improved
    * missing details in descriptions will have to be added
  contact:
    email: info@common-api.ch
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://webhook-notification.common-api.ch
tags:
  - name: event-notification-webhook
    description: Event notification webhook operations.
paths:
  /event-notifications:
    post:
      description: Send notification
      parameters:
        - $ref: ./components/parameters/header/correlation.yaml
        - $ref: ./components/parameters/header/api_version.yaml
        - $ref: ./components/parameters/header/event_type.yaml
        - $ref: ./components/parameters/header/event_id.yaml
        - $ref: ./components/parameters/header/event_created.yaml
        - $ref: ./components/parameters/header/event_subscription_id.yaml
      tags:
        - Notification Webhook
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./components/schemas/generic/EventNotification.yaml
      responses:
        '202':
          description: event-notification accepted
          headers:
            X-Correlation-ID:
              $ref: ./components/headers/X-Correlation-ID.yaml
        '400':
          $ref: ./components/responses/standard400.yaml
        '404':
          $ref: ./components/responses/standard404.yaml
        '429':
          $ref: ./components/responses/standard429.yaml
        '500':
          $ref: ./components/responses/standard500.yaml
        '501':
          $ref: ./components/responses/standard501.yaml
        '503':
          $ref: ./components/responses/standard503.yaml
        '504':
          $ref: ./components/responses/standard504.yaml
