name: 'SFTI Lint Specifications: Yaml Compliance'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      filenames:
        type: string
        default: '*.yaml'
        description: 'Files to be linted (list of files sperated by a whitespace). Default: *.yaml'

jobs:
  yaml-lint:
    uses: swissfintechinnovations/.github/.github/workflows/reusable-lint-yaml-workflow.yaml@24593077e659b279d3498bd70b68ec993fd6c0bd
    with:
      filenames: ${{ github.event.inputs.filenames || '*.yaml' }}
